name: ruqudi_app
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  introduction_screen: ^3.1.14
  google_fonts: ^6.2.1
  remixicon: ^1.2.0
  
  flutter_gen: any
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - assets/images/onboardings/flutter_logo.png
    - assets/images/onboardings/logo-preview.png
    - assets/images/onboardings/fullscreen.jpg
    - assets/images/onboardings/img1.jpg
    - assets/images/onboardings/img2.jpg
    - assets/images/onboardings/img3.jpg
    - assets/images/logo/logo.png
    - assets/images/logo/logo-single.png
    - assets/images/logo/logo-inline.png
    - assets/images/credit-card.png
    - assets/images/real-bank-card.png
    - assets/images/scan-card.png
